
services:
  db:
    ports:
      - 5432:5432
    networks:
      - bridge_network  
    build: ./database/

  app :
    networks:
      - bridge_network
    build: ./app/

networks:
  bridge_network:
    driver: bridge
