
services:
  db:
    ports:
      - 5432:5432
    networks:
      - bridge_network  
    build: ./database/
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app :
    networks:
      - bridge_network
    build: ./app/
#    restart: unless-stopped
    volumes:
      - data_base_csv:/var/data_base_csv

networks:
  bridge_network:
    driver: bridge

volumes:
    static_volume: {}
    postgres_data: {}
    data_base_csv:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./data_base_csv
