
services:
  db:
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - bridge_network  
    build: ./database/
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 80:8000
    env_file:
      - ./.env
    networks:
      - bridge_network
    depends_on:
          - db
    restart: always

  app :
    networks:
      - bridge_network
    build: ./app/
    restart: always
    env_file:
      - ./.env
    volumes:
      - data_base_csv:/var/data_base_csv

  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp_1
    ports:
      - "21:21"
    volumes:
      - data_base_csv:/sdo/
    env_file:
      - ./.env
    environment:
      - PUBLICHOST=${FTP_PUBLICHOST}
      - FTP_USER_NAME=${FTP_USER_NAME}
      - FTP_USER_PASS=${FTP_USER_PASS}
      - ADDED_FLAGS= "--tls=2"
      - TLS_CN="localhost"
      - TLS_ORG= "YourOrg"
      - TLS_C= "DE"



networks:
  bridge_network:
    driver: bridge

volumes:
    static_volume: {}
    postgres_data: {}
    data_base_csv:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./data_base_csv
